{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"inProcess"}],"languages":["swift"],"platforms":["Mac Catalyst"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mispeechkit\/sessionstate\/inprocess"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mispeechkit\/sessionstate\/inprocess"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/SessionState\/inProcess","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Audio data are processed."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"inProcess"}],"title":"SessionState.inProcess","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@miSpeechKit@E@SessionState@SessionStateInProcess","modules":[{"name":"miSpeechKit"}],"navigatorTitle":[{"kind":"identifier","text":"SessionStateInProcess"}]},"hierarchy":{"paths":[["doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit","doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/SessionState"]]},"references":{"doc://de.mediainterface.miSpeechKit/documentation/miSpeechKit/SessionState/inProcess":{"role":"symbol","title":"SessionState.inProcess","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"inProcess"}],"abstract":[{"type":"text","text":"Audio data are processed."}],"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/SessionState\/inProcess","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SessionStateInProcess"}],"url":"\/documentation\/mispeechkit\/sessionstate\/inprocess"},"doc://de.mediainterface.miSpeechKit/documentation/miSpeechKit/SessionState":{"role":"symbol","title":"SessionState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SessionState"}],"abstract":[{"type":"text","text":"The session state represent a recognition session. This values are set at recognition server."}],"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/SessionState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SessionState"}],"url":"\/documentation\/mispeechkit\/sessionstate"},"doc://de.mediainterface.miSpeechKit/documentation/miSpeechKit":{"role":"collection","title":"miSpeechKit","abstract":[{"type":"text","text":"miSpeechKit helps you to use speech recognition in your application."}],"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit","kind":"symbol","type":"topic","url":"\/documentation\/mispeechkit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SessionStateInProcess"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SessionStateInProcess"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SessionStateInProcess"}],"languages":["occ"],"platforms":["Mac Catalyst"]}]}},{"op":"replace","path":"\/references\/doc:~1~1de.mediainterface.miSpeechKit~1documentation~1miSpeechKit~1SessionState~1inProcess\/title","value":"SessionStateInProcess"},{"op":"replace","path":"\/references\/doc:~1~1de.mediainterface.miSpeechKit~1documentation~1miSpeechKit~1SessionState~1inProcess\/fragments","value":[{"kind":"identifier","text":"SessionStateInProcess"}]},{"op":"replace","path":"\/references\/doc:~1~1de.mediainterface.miSpeechKit~1documentation~1miSpeechKit~1SessionState\/title","value":"SessionState"},{"op":"replace","path":"\/references\/doc:~1~1de.mediainterface.miSpeechKit~1documentation~1miSpeechKit~1SessionState\/fragments","value":[{"kind":"identifier","text":"SessionState"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}