{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cleanupAsync"},{"kind":"text","text":"() "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"}],"languages":["swift"],"platforms":["Mac Catalyst"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mispeechkit\/irecognition\/cleanupasync()"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/IRecognition\/cleanupAsync()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"When this method is called, the resources at the speech recognition server are released again and the current session is destroyed."},{"type":"text","text":" "},{"type":"text","text":"This method should alwasy be called when the application is terminated."},{"type":"text","text":" "},{"type":"text","text":"During the operation, the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/IRecognition\/state"},{"type":"text","text":" changes to "},{"type":"reference","isActive":true,"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/SessionState\/unloading"},{"type":"text","text":" and is "},{"type":"reference","isActive":true,"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/SessionState\/closed"},{"type":"text","text":" when the method exits."}],"kind":"symbol","metadata":{"role":"symbol","title":"cleanupAsync()","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cleanupAsync"},{"kind":"text","text":"() "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"}],"symbolKind":"method","externalID":"s:11miSpeechKit12IRecognitionP12cleanupAsyncyyYaKF","required":true,"modules":[{"name":"miSpeechKit"}]},"hierarchy":{"paths":[["doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit","doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/IRecognition"]]},"references":{"doc://de.mediainterface.miSpeechKit/documentation/miSpeechKit/IRecognition":{"role":"symbol","title":"IRecognition","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IRecognition"}],"abstract":[{"type":"text","text":"Interface for communication with the speech recognition server in SpeaKING or MIRA medical."},{"type":"text","text":" "},{"type":"text","text":"This is where starting and stopping recognition is provided."},{"type":"text","text":" "},{"type":"text","text":"Messages are indicated with the corresponding events."}],"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/IRecognition","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IRecognition"}],"url":"\/documentation\/mispeechkit\/irecognition"},"doc://de.mediainterface.miSpeechKit/documentation/miSpeechKit/SessionState/closed":{"role":"symbol","title":"SessionState.closed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"closed"}],"abstract":[{"type":"text","text":"There is no speech recognition session yet and the speech recognizer has not been initialized."}],"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/SessionState\/closed","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SessionStateClosed"}],"url":"\/documentation\/mispeechkit\/sessionstate\/closed"},"doc://de.mediainterface.miSpeechKit/documentation/miSpeechKit/SessionState/unloading":{"role":"symbol","title":"SessionState.unloading","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unloading"}],"abstract":[{"type":"text","text":"The speech recognizer is dumped and all resources are released at the server."}],"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/SessionState\/unloading","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SessionStateUnloading"}],"url":"\/documentation\/mispeechkit\/sessionstate\/unloading"},"doc://de.mediainterface.miSpeechKit/documentation/miSpeechKit/IRecognition/state":{"role":"symbol","title":"state","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"state"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SessionState","preciseIdentifier":"c:@M@miSpeechKit@E@SessionState"}],"abstract":[{"type":"text","text":"Gets the current state of the speech recognition"}],"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/IRecognition\/state","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mispeechkit\/irecognition\/state"},"doc://de.mediainterface.miSpeechKit/documentation/miSpeechKit":{"role":"collection","title":"miSpeechKit","abstract":[{"type":"text","text":"miSpeechKit helps you to use speech recognition in your application."}],"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit","kind":"symbol","type":"topic","url":"\/documentation\/mispeechkit"},"doc://de.mediainterface.miSpeechKit/documentation/miSpeechKit/IRecognition/cleanupAsync()":{"role":"symbol","title":"cleanupAsync()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cleanupAsync"},{"kind":"text","text":"() "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"}],"abstract":[{"type":"text","text":"When this method is called, the resources at the speech recognition server are released again and the current session is destroyed."},{"type":"text","text":" "},{"type":"text","text":"This method should alwasy be called when the application is terminated."},{"type":"text","text":" "},{"type":"text","text":"During the operation, the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/IRecognition\/state"},{"type":"text","text":" changes to "},{"type":"reference","isActive":true,"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/SessionState\/unloading"},{"type":"text","text":" and is "},{"type":"reference","isActive":true,"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/SessionState\/closed"},{"type":"text","text":" when the method exits."}],"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/IRecognition\/cleanupAsync()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mispeechkit\/irecognition\/cleanupasync()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1de.mediainterface.miSpeechKit~1documentation~1miSpeechKit~1SessionState~1closed\/title","value":"SessionStateClosed"},{"op":"replace","path":"\/references\/doc:~1~1de.mediainterface.miSpeechKit~1documentation~1miSpeechKit~1SessionState~1closed\/fragments","value":[{"kind":"identifier","text":"SessionStateClosed"}]},{"op":"replace","path":"\/references\/doc:~1~1de.mediainterface.miSpeechKit~1documentation~1miSpeechKit~1SessionState~1unloading\/title","value":"SessionStateUnloading"},{"op":"replace","path":"\/references\/doc:~1~1de.mediainterface.miSpeechKit~1documentation~1miSpeechKit~1SessionState~1unloading\/fragments","value":[{"kind":"identifier","text":"SessionStateUnloading"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}