{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"previewChanged"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/Event","preciseIdentifier":"s:11miSpeechKit5EventC","text":"Event"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/PreviewChangedEventArgs","preciseIdentifier":"s:11miSpeechKit23PreviewChangedEventArgsC","text":"PreviewChangedEventArgs"},{"kind":"text","text":"> { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["Mac Catalyst"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mispeechkit\/irecognition\/previewchanged"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/IRecognition\/previewChanged","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Occurs when preview results are ready."},{"type":"text","text":" "},{"type":"text","text":"To get preview results, this needs to be configured when calling the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/IRecognition\/initializeAsync(_:)"},{"type":"text","text":" method."},{"type":"text","text":" "},{"type":"text","text":"To receive this event call "},{"type":"reference","isActive":true,"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/Event\/addHandler(handler:)"},{"type":"text","text":" and pass a method with a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/PreviewChangedEventArgs"},{"type":"text","text":" parameter as the handler."}],"kind":"symbol","metadata":{"role":"symbol","title":"previewChanged","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"previewChanged"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Event","preciseIdentifier":"s:11miSpeechKit5EventC"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"PreviewChangedEventArgs","preciseIdentifier":"s:11miSpeechKit23PreviewChangedEventArgsC"},{"kind":"text","text":">"}],"symbolKind":"property","externalID":"s:11miSpeechKit12IRecognitionP14previewChangedAA5EventCyAA07PreviewfG4ArgsCGvp","required":true,"modules":[{"name":"miSpeechKit"}]},"hierarchy":{"paths":[["doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit","doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/IRecognition"]]},"references":{"doc://de.mediainterface.miSpeechKit/documentation/miSpeechKit/IRecognition/cleanupAsync()":{"role":"symbol","title":"cleanupAsync()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cleanupAsync"},{"kind":"text","text":"() "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"}],"abstract":[{"type":"text","text":"When this method is called, the resources at the speech recognition server are released again and the current session is destroyed."},{"type":"text","text":" "},{"type":"text","text":"This method should alwasy be called when the application is terminated."},{"type":"text","text":" "},{"type":"text","text":"During the operation, the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/IRecognition\/state"},{"type":"text","text":" changes to "},{"type":"reference","isActive":true,"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/SessionState\/unloading"},{"type":"text","text":" and is "},{"type":"reference","isActive":true,"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/SessionState\/closed"},{"type":"text","text":" when the method exits."}],"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/IRecognition\/cleanupAsync()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mispeechkit\/irecognition\/cleanupasync()"},"doc://de.mediainterface.miSpeechKit/documentation/miSpeechKit/SessionState/loading":{"role":"symbol","title":"SessionState.loading","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"loading"}],"abstract":[{"type":"text","text":"Speech recogition is beeing prepared"}],"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/SessionState\/loading","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SessionStateLoading"}],"url":"\/documentation\/mispeechkit\/sessionstate\/loading"},"doc://de.mediainterface.miSpeechKit/documentation/miSpeechKit":{"role":"collection","title":"miSpeechKit","abstract":[{"type":"text","text":"miSpeechKit helps you to use speech recognition in your application."}],"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit","kind":"symbol","type":"topic","url":"\/documentation\/mispeechkit"},"doc://de.mediainterface.miSpeechKit/documentation/miSpeechKit/IRecognition":{"role":"symbol","title":"IRecognition","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IRecognition"}],"abstract":[{"type":"text","text":"Interface for communication with the speech recognition server in SpeaKING or MIRA medical."},{"type":"text","text":" "},{"type":"text","text":"This is where starting and stopping recognition is provided."},{"type":"text","text":" "},{"type":"text","text":"Messages are indicated with the corresponding events."}],"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/IRecognition","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IRecognition"}],"url":"\/documentation\/mispeechkit\/irecognition"},"doc://de.mediainterface.miSpeechKit/documentation/miSpeechKit/Event":{"role":"symbol","title":"Event","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Event"}],"abstract":[],"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/Event","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Event"}],"url":"\/documentation\/mispeechkit\/event"},"doc://de.mediainterface.miSpeechKit/documentation/miSpeechKit/SessionState/ready":{"role":"symbol","title":"SessionState.ready","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"ready"}],"abstract":[{"type":"text","text":"Speech recognition is ready to receive data."}],"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/SessionState\/ready","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SessionStateReady"}],"url":"\/documentation\/mispeechkit\/sessionstate\/ready"},"doc://de.mediainterface.miSpeechKit/documentation/miSpeechKit/SessionState/created":{"role":"symbol","title":"SessionState.created","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"created"}],"abstract":[{"type":"text","text":"A connection with the recognition service has been successfully initiated."}],"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/SessionState\/created","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SessionStateCreated"}],"url":"\/documentation\/mispeechkit\/sessionstate\/created"},"doc://de.mediainterface.miSpeechKit/documentation/miSpeechKit/Event/addHandler(handler:)":{"role":"symbol","title":"addHandler(handler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addHandler"},{"kind":"text","text":"("},{"kind":"externalParam","text":"handler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"EventHandler","preciseIdentifier":"s:11miSpeechKit5EventC0D7Handlera"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/Event\/addHandler(handler:)","kind":"symbol","type":"topic","url":"\/documentation\/mispeechkit\/event\/addhandler(handler:)"},"doc://de.mediainterface.miSpeechKit/documentation/miSpeechKit/IRecognition/errorOccured":{"role":"symbol","title":"errorOccured","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorOccured"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Event","preciseIdentifier":"s:11miSpeechKit5EventC"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"ErrorOccuredEventArgs","preciseIdentifier":"s:11miSpeechKit21ErrorOccuredEventArgsC"},{"kind":"text","text":">"}],"abstract":[{"type":"text","text":"Occurs when an error is throws during communication or directly in the speech recognition server."},{"type":"text","text":" "},{"type":"text","text":"To receive this event call "},{"type":"reference","isActive":true,"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/Event\/addHandler(handler:)"},{"type":"text","text":" and pass a method with a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/ErrorOccuredEventArgs"},{"type":"text","text":" parameter as the handler."}],"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/IRecognition\/errorOccured","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mispeechkit\/irecognition\/erroroccured"},"doc://de.mediainterface.miSpeechKit/documentation/miSpeechKit/IRecognition/initializeAsync(_:)":{"role":"symbol","title":"initializeAsync(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initializeAsync"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"IRecognitionContext","preciseIdentifier":"s:11miSpeechKit19IRecognitionContextP"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"}],"abstract":[{"type":"text","text":"Establishes the connection to the speech recognition server and creates a new speech recognition session."},{"type":"text","text":" "},{"type":"text","text":"During "},{"type":"reference","isActive":true,"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/IRecognition\/initializeAsync(_:)"},{"type":"text","text":", the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/IRecognition\/state"},{"type":"text","text":" property changes first to "},{"type":"reference","isActive":true,"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/SessionState\/created"},{"type":"text","text":" and then to "},{"type":"reference","isActive":true,"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/SessionState\/loading"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"If the initialization is completed successfully, the state "},{"type":"reference","isActive":true,"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/SessionState\/ready"},{"type":"text","text":" is reached."},{"type":"text","text":" "},{"type":"text","text":"Errors are reported using the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/IRecognition\/errorOccured"},{"type":"text","text":" event."},{"type":"text","text":" "},{"type":"text","text":"To end a speech recognition session the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/IRecognition\/cleanupAsync()"},{"type":"text","text":" method must be called."}],"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/IRecognition\/initializeAsync(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mispeechkit\/irecognition\/initializeasync(_:)"},"doc://de.mediainterface.miSpeechKit/documentation/miSpeechKit/IRecognition/state":{"role":"symbol","title":"state","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"state"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SessionState","preciseIdentifier":"c:@M@miSpeechKit@E@SessionState"}],"abstract":[{"type":"text","text":"Gets the current state of the speech recognition"}],"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/IRecognition\/state","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mispeechkit\/irecognition\/state"},"doc://de.mediainterface.miSpeechKit/documentation/miSpeechKit/IRecognition/previewChanged":{"role":"symbol","title":"previewChanged","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"previewChanged"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Event","preciseIdentifier":"s:11miSpeechKit5EventC"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"PreviewChangedEventArgs","preciseIdentifier":"s:11miSpeechKit23PreviewChangedEventArgsC"},{"kind":"text","text":">"}],"abstract":[{"type":"text","text":"Occurs when preview results are ready."},{"type":"text","text":" "},{"type":"text","text":"To get preview results, this needs to be configured when calling the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/IRecognition\/initializeAsync(_:)"},{"type":"text","text":" method."},{"type":"text","text":" "},{"type":"text","text":"To receive this event call "},{"type":"reference","isActive":true,"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/Event\/addHandler(handler:)"},{"type":"text","text":" and pass a method with a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/PreviewChangedEventArgs"},{"type":"text","text":" parameter as the handler."}],"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/IRecognition\/previewChanged","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mispeechkit\/irecognition\/previewchanged"},"doc://de.mediainterface.miSpeechKit/documentation/miSpeechKit/PreviewChangedEventArgs":{"role":"symbol","title":"PreviewChangedEventArgs","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PreviewChangedEventArgs"}],"abstract":[{"type":"text","text":"Provides data to evaluate the preview results."}],"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/PreviewChangedEventArgs","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PreviewChangedEventArgs"}],"url":"\/documentation\/mispeechkit\/previewchangedeventargs"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1de.mediainterface.miSpeechKit~1documentation~1miSpeechKit~1SessionState~1loading\/title","value":"SessionStateLoading"},{"op":"replace","path":"\/references\/doc:~1~1de.mediainterface.miSpeechKit~1documentation~1miSpeechKit~1SessionState~1loading\/fragments","value":[{"kind":"identifier","text":"SessionStateLoading"}]},{"op":"replace","path":"\/references\/doc:~1~1de.mediainterface.miSpeechKit~1documentation~1miSpeechKit~1SessionState~1ready\/title","value":"SessionStateReady"},{"op":"replace","path":"\/references\/doc:~1~1de.mediainterface.miSpeechKit~1documentation~1miSpeechKit~1SessionState~1ready\/fragments","value":[{"kind":"identifier","text":"SessionStateReady"}]},{"op":"replace","path":"\/references\/doc:~1~1de.mediainterface.miSpeechKit~1documentation~1miSpeechKit~1SessionState~1created\/title","value":"SessionStateCreated"},{"op":"replace","path":"\/references\/doc:~1~1de.mediainterface.miSpeechKit~1documentation~1miSpeechKit~1SessionState~1created\/fragments","value":[{"kind":"identifier","text":"SessionStateCreated"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}