{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startAsync"},{"kind":"text","text":"("},{"kind":"externalParam","text":"previousText"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"followingText"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"}],"languages":["swift"],"platforms":["Mac Catalyst"]}]},{"kind":"parameters","parameters":[{"name":"previousText","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Specifies the text that is located before insertion position."}]}]},{"name":"followingText","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Specifies the text that is located after insertion position."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If start is called and the soeech recognition server is not yet ready or there is no longer a connection to the speech recognition server, then the audio is cached and set to the server later."}]}],"type":"aside","name":"Remark"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"To improve speech recognition quality, it is very important to transmit the text context at each startup."}]}],"type":"aside","name":"Remark"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An error of type "},{"type":"codeVoice","code":"SpeechError"}]}],"type":"aside","name":"Throws"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mispeechkit\/irecognition\/startasync(previoustext:followingtext:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/IRecognition\/startAsync(previousText:followingText:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Start the speech recognition."},{"type":"text","text":" "},{"type":"text","text":"A text context can be passed using the parameters "},{"type":"codeVoice","code":"previousText"},{"type":"text","text":" and "},{"type":"codeVoice","code":"followingText"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"The speech recognition will then use this text context as a basis for recognizing new content and will also use it to determine upper and lower case."},{"type":"text","text":" "},{"type":"text","text":"Audio data are automaticlly received from the default audio device and sent to the speech recognition server."},{"type":"text","text":" "},{"type":"text","text":"If the recognition could be started successfully, the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/IRecognition\/state"},{"type":"text","text":" changes to "},{"type":"reference","isActive":true,"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/SessionState\/inProcess"},{"type":"text","text":","},{"type":"text","text":" "},{"type":"text","text":"Recognition results are automatically reported during recognition and the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/IRecognition\/resultChanged"},{"type":"text","text":" is raised."},{"type":"text","text":" "},{"type":"text","text":"To stop the recognition and recording call "},{"type":"reference","isActive":true,"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/IRecognition\/stopAsync()"}],"kind":"symbol","metadata":{"role":"symbol","title":"startAsync(previousText:followingText:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startAsync"},{"kind":"text","text":"("},{"kind":"externalParam","text":"previousText"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"followingText"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"}],"symbolKind":"method","externalID":"s:11miSpeechKit12IRecognitionP10startAsync12previousText09followingH0ySSSg_AGtYaKF","required":true,"modules":[{"name":"miSpeechKit"}]},"hierarchy":{"paths":[["doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit","doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/IRecognition"]]},"references":{"doc://de.mediainterface.miSpeechKit/documentation/miSpeechKit/SessionState/ready":{"role":"symbol","title":"SessionState.ready","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"ready"}],"abstract":[{"type":"text","text":"Speech recognition is ready to receive data."}],"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/SessionState\/ready","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SessionStateReady"}],"url":"\/documentation\/mispeechkit\/sessionstate\/ready"},"doc://de.mediainterface.miSpeechKit/documentation/miSpeechKit/IRecognition/state":{"role":"symbol","title":"state","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"state"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SessionState","preciseIdentifier":"c:@M@miSpeechKit@E@SessionState"}],"abstract":[{"type":"text","text":"Gets the current state of the speech recognition"}],"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/IRecognition\/state","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mispeechkit\/irecognition\/state"},"doc://de.mediainterface.miSpeechKit/documentation/miSpeechKit/IRecognition/startAsync(previousText:followingText:)":{"role":"symbol","title":"startAsync(previousText:followingText:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startAsync"},{"kind":"text","text":"("},{"kind":"externalParam","text":"previousText"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"followingText"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"}],"abstract":[{"type":"text","text":"Start the speech recognition."},{"type":"text","text":" "},{"type":"text","text":"A text context can be passed using the parameters "},{"type":"codeVoice","code":"previousText"},{"type":"text","text":" and "},{"type":"codeVoice","code":"followingText"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"The speech recognition will then use this text context as a basis for recognizing new content and will also use it to determine upper and lower case."},{"type":"text","text":" "},{"type":"text","text":"Audio data are automaticlly received from the default audio device and sent to the speech recognition server."},{"type":"text","text":" "},{"type":"text","text":"If the recognition could be started successfully, the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/IRecognition\/state"},{"type":"text","text":" changes to "},{"type":"reference","isActive":true,"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/SessionState\/inProcess"},{"type":"text","text":","},{"type":"text","text":" "},{"type":"text","text":"Recognition results are automatically reported during recognition and the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/IRecognition\/resultChanged"},{"type":"text","text":" is raised."},{"type":"text","text":" "},{"type":"text","text":"To stop the recognition and recording call "},{"type":"reference","isActive":true,"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/IRecognition\/stopAsync()"}],"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/IRecognition\/startAsync(previousText:followingText:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mispeechkit\/irecognition\/startasync(previoustext:followingtext:)"},"doc://de.mediainterface.miSpeechKit/documentation/miSpeechKit/IRecognition/stopAsync()":{"role":"symbol","title":"stopAsync()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopAsync"},{"kind":"text","text":"() "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"}],"abstract":[{"type":"text","text":"Stops audio recording and speech recognition and forces the speech recognizer to submit the results."},{"type":"text","text":" "},{"type":"text","text":"The recording can be restarted with "},{"type":"reference","isActive":true,"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/IRecognition\/startAsync(previousText:followingText:)"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"It is important to set the text context to imporve speech recognition."},{"type":"text","text":" "},{"type":"text","text":"If speech recognition could be stopped successfully, the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/IRecognition\/state"},{"type":"text","text":" changes back to "},{"type":"reference","isActive":true,"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/SessionState\/ready"},{"type":"text","text":"."}],"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/IRecognition\/stopAsync()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mispeechkit\/irecognition\/stopasync()"},"doc://de.mediainterface.miSpeechKit/documentation/miSpeechKit/IRecognition/resultChanged":{"role":"symbol","title":"resultChanged","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"resultChanged"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Event","preciseIdentifier":"s:11miSpeechKit5EventC"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"ResultChangedEventArgs","preciseIdentifier":"s:11miSpeechKit22ResultChangedEventArgsC"},{"kind":"text","text":">"}],"abstract":[{"type":"text","text":"Occurs when results of speech recognition are ready."},{"type":"text","text":" "},{"type":"text","text":"To receive this event call "},{"type":"reference","isActive":true,"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/Event\/addHandler(handler:)"},{"type":"text","text":" and pass a method with a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/ResultChangedEventArgs"},{"type":"text","text":" parameter as the handler."}],"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/IRecognition\/resultChanged","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mispeechkit\/irecognition\/resultchanged"},"doc://de.mediainterface.miSpeechKit/documentation/miSpeechKit/ResultChangedEventArgs":{"role":"symbol","title":"ResultChangedEventArgs","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResultChangedEventArgs"}],"abstract":[{"type":"text","text":"Provides data to process recognition results."}],"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/ResultChangedEventArgs","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ResultChangedEventArgs"}],"url":"\/documentation\/mispeechkit\/resultchangedeventargs"},"doc://de.mediainterface.miSpeechKit/documentation/miSpeechKit/SessionState/inProcess":{"role":"symbol","title":"SessionState.inProcess","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"inProcess"}],"abstract":[{"type":"text","text":"Audio data are processed."}],"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/SessionState\/inProcess","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SessionStateInProcess"}],"url":"\/documentation\/mispeechkit\/sessionstate\/inprocess"},"doc://de.mediainterface.miSpeechKit/documentation/miSpeechKit":{"role":"collection","title":"miSpeechKit","abstract":[{"type":"text","text":"miSpeechKit helps you to use speech recognition in your application."}],"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit","kind":"symbol","type":"topic","url":"\/documentation\/mispeechkit"},"doc://de.mediainterface.miSpeechKit/documentation/miSpeechKit/IRecognition":{"role":"symbol","title":"IRecognition","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IRecognition"}],"abstract":[{"type":"text","text":"Interface for communication with the speech recognition server in SpeaKING or MIRA medical."},{"type":"text","text":" "},{"type":"text","text":"This is where starting and stopping recognition is provided."},{"type":"text","text":" "},{"type":"text","text":"Messages are indicated with the corresponding events."}],"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/IRecognition","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IRecognition"}],"url":"\/documentation\/mispeechkit\/irecognition"},"doc://de.mediainterface.miSpeechKit/documentation/miSpeechKit/Event/addHandler(handler:)":{"role":"symbol","title":"addHandler(handler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addHandler"},{"kind":"text","text":"("},{"kind":"externalParam","text":"handler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"EventHandler","preciseIdentifier":"s:11miSpeechKit5EventC0D7Handlera"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/Event\/addHandler(handler:)","kind":"symbol","type":"topic","url":"\/documentation\/mispeechkit\/event\/addhandler(handler:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1de.mediainterface.miSpeechKit~1documentation~1miSpeechKit~1SessionState~1ready\/title","value":"SessionStateReady"},{"op":"replace","path":"\/references\/doc:~1~1de.mediainterface.miSpeechKit~1documentation~1miSpeechKit~1SessionState~1ready\/fragments","value":[{"kind":"identifier","text":"SessionStateReady"}]},{"op":"replace","path":"\/references\/doc:~1~1de.mediainterface.miSpeechKit~1documentation~1miSpeechKit~1SessionState~1inProcess\/title","value":"SessionStateInProcess"},{"op":"replace","path":"\/references\/doc:~1~1de.mediainterface.miSpeechKit~1documentation~1miSpeechKit~1SessionState~1inProcess\/fragments","value":[{"kind":"identifier","text":"SessionStateInProcess"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}