{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IRecognitionContext"}],"languages":["swift"],"platforms":["Mac Catalyst"]}]},{"kind":"content","content":[{"anchor":"Reference","level":1,"type":"heading","text":"Reference"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/MISpeech\/createRecognitionContext(user:vocabulary:previewResults:debug:language:audioFormat:)"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/IRecognition\/initializeAsync(_:)"}]}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mispeechkit\/irecognitioncontext"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/IRecognitionContext","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A context used to initialize a speech recognition session."},{"type":"text","text":" "},{"type":"text","text":"This provides all the essential settings, such as user and vocabulary."},{"type":"text","text":" "},{"type":"text","text":"The only mandatory property is the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/IRecognitionContext\/user"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IRecognitionContext"}],"title":"IRecognitionContext","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"s:11miSpeechKit19IRecognitionContextP","modules":[{"name":"miSpeechKit"}],"navigatorTitle":[{"kind":"identifier","text":"IRecognitionContext"}]},"hierarchy":{"paths":[["doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/IRecognitionContext\/audioFormat","doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/IRecognitionContext\/debug","doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/IRecognitionContext\/language","doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/IRecognitionContext\/previewResults","doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/IRecognitionContext\/user","doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/IRecognitionContext\/vocabulary"]}],"references":{"doc://de.mediainterface.miSpeechKit/documentation/miSpeechKit/IRecognition/cleanupAsync()":{"role":"symbol","title":"cleanupAsync()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cleanupAsync"},{"kind":"text","text":"() "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"}],"abstract":[{"type":"text","text":"When this method is called, the resources at the speech recognition server are released again and the current session is destroyed."},{"type":"text","text":" "},{"type":"text","text":"This method should alwasy be called when the application is terminated."},{"type":"text","text":" "},{"type":"text","text":"During the operation, the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/IRecognition\/state"},{"type":"text","text":" changes to "},{"type":"reference","isActive":true,"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/SessionState\/unloading"},{"type":"text","text":" and is "},{"type":"reference","isActive":true,"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/SessionState\/closed"},{"type":"text","text":" when the method exits."}],"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/IRecognition\/cleanupAsync()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mispeechkit\/irecognition\/cleanupasync()"},"doc://de.mediainterface.miSpeechKit/documentation/miSpeechKit/IRecognitionContext/debug":{"role":"symbol","title":"debug","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"debug"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Specifies whether to record messages and other log information at the speech recognition server for later analysis."}],"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/IRecognitionContext\/debug","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mispeechkit\/irecognitioncontext\/debug"},"doc://de.mediainterface.miSpeechKit/documentation/miSpeechKit/IRecognition/errorOccured":{"role":"symbol","title":"errorOccured","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorOccured"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Event","preciseIdentifier":"s:11miSpeechKit5EventC"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"ErrorOccuredEventArgs","preciseIdentifier":"s:11miSpeechKit21ErrorOccuredEventArgsC"},{"kind":"text","text":">"}],"abstract":[{"type":"text","text":"Occurs when an error is throws during communication or directly in the speech recognition server."},{"type":"text","text":" "},{"type":"text","text":"To receive this event call "},{"type":"reference","isActive":true,"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/Event\/addHandler(handler:)"},{"type":"text","text":" and pass a method with a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/ErrorOccuredEventArgs"},{"type":"text","text":" parameter as the handler."}],"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/IRecognition\/errorOccured","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mispeechkit\/irecognition\/erroroccured"},"doc://de.mediainterface.miSpeechKit/documentation/miSpeechKit/IRecognitionContext/vocabulary":{"role":"symbol","title":"vocabulary","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"vocabulary"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Gets the vocabulary used for speech recognition."}],"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/IRecognitionContext\/vocabulary","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mispeechkit\/irecognitioncontext\/vocabulary"},"doc://de.mediainterface.miSpeechKit/documentation/miSpeechKit/IRecognitionContext/previewResults":{"role":"symbol","title":"previewResults","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"previewResults"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Specifies whether or not preview results are transmitted during speech recognition."}],"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/IRecognitionContext\/previewResults","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mispeechkit\/irecognitioncontext\/previewresults"},"doc://de.mediainterface.miSpeechKit/documentation/miSpeechKit/IRecognitionContext/user":{"role":"symbol","title":"user","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"user"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"Gets the user that is used for speech recognition."}],"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/IRecognitionContext\/user","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mispeechkit\/irecognitioncontext\/user"},"doc://de.mediainterface.miSpeechKit/documentation/miSpeechKit/SessionState/ready":{"role":"symbol","title":"SessionState.ready","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"ready"}],"abstract":[{"type":"text","text":"Speech recognition is ready to receive data."}],"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/SessionState\/ready","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SessionStateReady"}],"url":"\/documentation\/mispeechkit\/sessionstate\/ready"},"doc://de.mediainterface.miSpeechKit/documentation/miSpeechKit":{"role":"collection","title":"miSpeechKit","abstract":[{"type":"text","text":"miSpeechKit helps you to use speech recognition in your application."}],"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit","kind":"symbol","type":"topic","url":"\/documentation\/mispeechkit"},"doc://de.mediainterface.miSpeechKit/documentation/miSpeechKit/SessionState/loading":{"role":"symbol","title":"SessionState.loading","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"loading"}],"abstract":[{"type":"text","text":"Speech recogition is beeing prepared"}],"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/SessionState\/loading","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SessionStateLoading"}],"url":"\/documentation\/mispeechkit\/sessionstate\/loading"},"doc://de.mediainterface.miSpeechKit/documentation/miSpeechKit/IRecognitionContext/language":{"role":"symbol","title":"language","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"language"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Specifies the language that is used for speech recognition."}],"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/IRecognitionContext\/language","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mispeechkit\/irecognitioncontext\/language"},"doc://de.mediainterface.miSpeechKit/documentation/miSpeechKit/IRecognition/initializeAsync(_:)":{"role":"symbol","title":"initializeAsync(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initializeAsync"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"IRecognitionContext","preciseIdentifier":"s:11miSpeechKit19IRecognitionContextP"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"}],"abstract":[{"type":"text","text":"Establishes the connection to the speech recognition server and creates a new speech recognition session."},{"type":"text","text":" "},{"type":"text","text":"During "},{"type":"reference","isActive":true,"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/IRecognition\/initializeAsync(_:)"},{"type":"text","text":", the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/IRecognition\/state"},{"type":"text","text":" property changes first to "},{"type":"reference","isActive":true,"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/SessionState\/created"},{"type":"text","text":" and then to "},{"type":"reference","isActive":true,"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/SessionState\/loading"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"If the initialization is completed successfully, the state "},{"type":"reference","isActive":true,"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/SessionState\/ready"},{"type":"text","text":" is reached."},{"type":"text","text":" "},{"type":"text","text":"Errors are reported using the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/IRecognition\/errorOccured"},{"type":"text","text":" event."},{"type":"text","text":" "},{"type":"text","text":"To end a speech recognition session the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/IRecognition\/cleanupAsync()"},{"type":"text","text":" method must be called."}],"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/IRecognition\/initializeAsync(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mispeechkit\/irecognition\/initializeasync(_:)"},"doc://de.mediainterface.miSpeechKit/documentation/miSpeechKit/MISpeech/createRecognitionContext(user:vocabulary:previewResults:debug:language:audioFormat:)":{"role":"symbol","title":"createRecognitionContext(user:vocabulary:previewResults:debug:language:audioFormat:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createRecognitionContext"},{"kind":"text","text":"("},{"kind":"externalParam","text":"user"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"vocabulary"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"previewResults"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"debug"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"language"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"audioFormat"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AudioFormat","preciseIdentifier":"s:11miSpeechKit11AudioFormatO"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"IRecognitionContext","preciseIdentifier":"s:11miSpeechKit19IRecognitionContextP"}],"abstract":[],"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/MISpeech\/createRecognitionContext(user:vocabulary:previewResults:debug:language:audioFormat:)","kind":"symbol","type":"topic","url":"\/documentation\/mispeechkit\/mispeech\/createrecognitioncontext(user:vocabulary:previewresults:debug:language:audioformat:)"},"doc://de.mediainterface.miSpeechKit/documentation/miSpeechKit/IRecognitionContext":{"role":"symbol","title":"IRecognitionContext","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IRecognitionContext"}],"abstract":[{"type":"text","text":"A context used to initialize a speech recognition session."},{"type":"text","text":" "},{"type":"text","text":"This provides all the essential settings, such as user and vocabulary."},{"type":"text","text":" "},{"type":"text","text":"The only mandatory property is the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/IRecognitionContext\/user"},{"type":"text","text":"."}],"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/IRecognitionContext","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IRecognitionContext"}],"url":"\/documentation\/mispeechkit\/irecognitioncontext"},"doc://de.mediainterface.miSpeechKit/documentation/miSpeechKit/IRecognition/state":{"role":"symbol","title":"state","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"state"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SessionState","preciseIdentifier":"c:@M@miSpeechKit@E@SessionState"}],"abstract":[{"type":"text","text":"Gets the current state of the speech recognition"}],"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/IRecognition\/state","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mispeechkit\/irecognition\/state"},"doc://de.mediainterface.miSpeechKit/documentation/miSpeechKit/IRecognitionContext/audioFormat":{"role":"symbol","title":"audioFormat","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioFormat"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AudioFormat","preciseIdentifier":"s:11miSpeechKit11AudioFormatO"}],"abstract":[{"type":"text","text":"Specifies the audio format that is used to transfer the audio data to the recognition service."}],"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/IRecognitionContext\/audioFormat","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/mispeechkit\/irecognitioncontext\/audioformat"},"doc://de.mediainterface.miSpeechKit/documentation/miSpeechKit/SessionState/created":{"role":"symbol","title":"SessionState.created","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"created"}],"abstract":[{"type":"text","text":"A connection with the recognition service has been successfully initiated."}],"identifier":"doc:\/\/de.mediainterface.miSpeechKit\/documentation\/miSpeechKit\/SessionState\/created","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SessionStateCreated"}],"url":"\/documentation\/mispeechkit\/sessionstate\/created"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1de.mediainterface.miSpeechKit~1documentation~1miSpeechKit~1SessionState~1ready\/title","value":"SessionStateReady"},{"op":"replace","path":"\/references\/doc:~1~1de.mediainterface.miSpeechKit~1documentation~1miSpeechKit~1SessionState~1ready\/fragments","value":[{"kind":"identifier","text":"SessionStateReady"}]},{"op":"replace","path":"\/references\/doc:~1~1de.mediainterface.miSpeechKit~1documentation~1miSpeechKit~1SessionState~1loading\/title","value":"SessionStateLoading"},{"op":"replace","path":"\/references\/doc:~1~1de.mediainterface.miSpeechKit~1documentation~1miSpeechKit~1SessionState~1loading\/fragments","value":[{"kind":"identifier","text":"SessionStateLoading"}]},{"op":"replace","path":"\/references\/doc:~1~1de.mediainterface.miSpeechKit~1documentation~1miSpeechKit~1SessionState~1created\/title","value":"SessionStateCreated"},{"op":"replace","path":"\/references\/doc:~1~1de.mediainterface.miSpeechKit~1documentation~1miSpeechKit~1SessionState~1created\/fragments","value":[{"kind":"identifier","text":"SessionStateCreated"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}